config/routes.rb
Rails.application.routes.draw do

  scope '/dashboard' do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end 

  scope '/:store_id' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :dashboard do 
      root 'products#index'
      resources :stores, only: [:new, :create, :edit, :update], path: '/' do 
        resources :products
        resources :orders, only: [:index, :show, :destroy]
        resources :order_lines, only: [:index, :show]
        resources :customers, only: [:index]
      end
  end

   

  root 'welcome#index'

  get ':store_id', to: 'stores#show', as: 'store'
  resources :stores, only: [:show], path: '/' do 
    resource :cart, only: [:show]
    resources :products, only: [:index, :show]
    resources :orders, only: [:index, :show]
    get '/orders/:id/confirmation' => 'orders#confirmation', as: 'confirmation'
    resources :order_lines, only: [:create, :update, :destroy]
    resources :charges, only: [:new, :create]
  end   

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
layout 'customer'


  def show
  	@order_lines = current_order.order_lines
  end

  def clear_cart
  	session["current_order_id_#{current_store.id}"] = nil
  	redirect_to store_path
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well"> 
	<div class="row">
		<div class="col-md-4">

			<h4><strong><%= link_to product.title, store_product_path(current_store.id, product.id) %></strong></h4>
			
		</div>
		
		<div class="col-md-8">				
			
				<%= form_for :order_line, url: store_order_line_path(current_store.id, order_line.id), method: :patch, remote: true do |f| %>

					<h4 class="text-right">Unit Price: $<%= order_line.product.price_in_cents %></h4>
					<div class="row">
						<div class="col-xs-4">
							<%= f.number_field :quantity, value: order_line.quantity, class: "form-control", min: 1 %>
							<%= f.hidden_field :product_id, value: product.id %>
						</div>
						<div class="col-xs-8 text-right">
							<div class="btn-group">
								<%= f.submit "Update Quantity", class: "btn btn-success" %>		
								<%= link_to "Delete", store_order_line_path(current_store.id, order_line.id), method: :delete, data: {confirm: "Are you sure you want to delete the product '#{order_line.product.title}'from your cart?"}, class: "btn btn-danger", remote: true %>  	
							</div>
						</div>
					</div>

					<h4 class="subtotal">Subtotal: $<%= order_line.total_price %></h4>
				<% end %>
				
			           
	        	

		</div>
	</div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_line.nil? && @order_line.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% @order_line.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<% unless @order_lines.present? %>
	<p class="text-center">
		There are no items in your shopping cart. Please <%= link_to "go back", store_products_path %> and add some items in your cart.
	</p>
<% else %>
	<% @order_lines.each do |order_line| %>
		<%= render 'carts/cart_row', product: order_line.product, order_line: order_line, show_total: true %>
	<% end %>
<% end %>

<div class="row">
	<div class="col-md-3 col-md-offset-6">
		<h1>Total: $<%= current_order.subtotal %></h1>
	</div>
	<div class="col-md-2" >
		<h1><%= link_to "Checkout", new_store_charge_path, class: "btn btn-success" %></h1>
	</div>
</div>

app/views/carts/show.html.erb
<div class="shopping-cart">	
	<%= render "shopping_cart" %>
</div>