config/routes.rb
Rails.application.routes.draw do

  scope '/dashboard' do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end 

  scope '/:store_id' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :dashboard do 
      root 'products#index'
      resources :stores, only: [:new, :create, :edit, :update], path: '/' do 
        resources :products
        resources :orders, only: [:index, :show, :destroy]
        resources :order_lines, only: [:index, :show]
        resources :customers, only: [:index]
      end
  end

   

  root 'welcome#index'

  get ':store_id', to: 'stores#show', as: 'store'
  resources :stores, only: [:show], path: '/' do 
    resource :cart, only: [:show]
    resources :products, only: [:index, :show]
    resources :orders, only: [:index, :show]
    get '/orders/:id/confirmation' => 'orders#confirmation', as: 'confirmation'
    resources :order_lines, only: [:create, :update, :destroy]
    resources :charges, only: [:new, :create]
  end   

end

app/models/product.rb
class Product < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title, use: :slugged

	mount_uploader :image, ImageUploader

	belongs_to :store
	has_many :order_lines


	validates :store, presence: true
	validates :title, length: { minimum: 5}, presence: true
	validates :description, length: { minimum: 10}, presence: true
	validates :sku, presence: true, numericality: { only_integer: true }
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :count, presence: true, numericality: { only_integer: true}

	# Add a boolean :active to indicate if product is live or not?

	def price # getter for rent in cents
		read_attribute(:price_in_cents)
	end

	def price=(v) # setter for rent in cents
		# v = v.to_s
		# v = v.gsub(',','')
		# v = v.gsub('$','')

		v.to_i if v.is_a?(String)

		write_attribute(:price_in_cents, v * 100)
	end

end

app/controllers/dashboard/customers_controller.rb
class Dashboard::CustomersController < DashboardController

before_action :get_store
before_action :authenticate_owner!

def index
	@customers = @store.customers.all
end

# def show
# 	@customer = @store.customers.find(params[:id])
# end



	private

	def get_store
	  @store = Store.friendly.find(params[:store_id])
	end


end

app/controllers/dashboard/order_lines_controller.rb
class Dashboard::OrderLinesController < DashboardController

    before_action :authenticate_owner!
	before_action :get_store, only: [:index, :show]

	def index
		@order = @store.orders.find(params[:order_id])
		@order_lines = @order.order_lines.all 
	end

	def show
		@order = @store.orders.find(params[:order_id])
		@order_line = @store.orders.find(params[:id])
	end

	
	private
  
	  def order_line_params
	    params.require(:order_line).permit(:product, :order, :quantity, :price)
	  end

	  def get_store
	  	@store = Store.friendly.find(params[:store_id])
	  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < DashboardController

#order belongs to a store
    before_action :authenticate_owner!
	before_action :get_store, only: [:index, :show]

	def index
		@orders = @store.orders.all
	end

	def show
		@order = @store.orders.find(params[:id])
	end


	def destroy
		@order = @store.orders.find(params[:id])
	    authorize @order 
	    
	    if @order.destroy
	      flash[:notice] = "Order was deleted successfully."
	      redirect_to :index
	    else
	      flash[:error] = "There was an error deleting the order."
	      render :show
	    end
	end

 private
  
  def order_params
     params.require(:order).permit(:customer, :total, :completed, :date_paid)
  end

  def get_store
	 @store = Store.friendly.find(params[:store_id])
  end

end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController

  # before_action :authenticate_owner!, except: [:index, :new]
  before_action :get_store

  after_filter { flash.discard if request.xhr? }

  def index
    @products = @store.products.all
  end

  def show
    @product = Product.friendly.find(params[:id])
  end

  def new
    @product = Product.new
    authorize @product
  end


  def create
    @product = Product.new
    @product = @store.products.build(product_params)

    authorize @product

    if @product.save
      flash[:notice] = "Product was added to store"
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error saving the product."
      render :new
    end
  end


  def edit
    @product = Product.friendly.find(params[:id])
    authorize @product
  end


  def update
    @product = Product.friendly.find(params[:id])
    authorize @product

    @product.assign_attributes(product_params)

    if @product.save
      flash[:notice] = "Product was updated."
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error saving the product. Please try again."
      render :edit
    end
  end

  def destroy
    @product = Product.friendly.find(params[:id])
    authorize @product

    if @product.destroy
      flash[:notice] = "\"#{@product.title}\" was deleted successfully."
    else
      flash[:error] = "There was an error deleting the product."
    end
    @products = @store.products.all

    if @product.delete
      flash[:notice] = "Product was deleted."
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error deleting the product. Please try again."
      render :index
    end
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :sku, :price_in_cents, :count, :image, :remove_image)
  end


  def get_store
   @store = Store.friendly.find(params[:store_id])
  end

end

app/controllers/dashboard/stores_controller.rb
class Dashboard::StoresController < DashboardController

    before_action :authenticate_owner!, only: [:edit, :update]

	def show
		@store = Store.friendly.find(params[:id])
	end

	def new
		@store = Store.new
	end

	def create
		@owner = current_user
		@store = @owner.stores.build(store_params)

		if @store.save
			flash[:notice] = "Store was created."
	  		redirect_to dashboard_store_products_path(@store.id)
	    else
	      flash[:error] = "There was an error creating the store."
	      render :new
	    end
  	end


   	def edit
   		@store = Store.friendly.find(params[:id])
   	end


	 def update
	 	@store = Store.friendly.find(params[:id])
	 	@store.assign_attributes(store_params)

	 	if @store.save
	 		flash[:notice] = "Store was updated."
	 		redirect_to dashboard_store_products_path
	 	else
	 		flash[:error] = "There was an error updating the store. Please try again."
	 		render :edit
	 	end
	 end


  private

  def store_params
    params.require(:store).permit(:name, :owner_id, :description, :about, :action_call)
  end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	layout 'dashboard'
	# to correspond with the dashboard layouts for view 

	# before_action :check_if_owner

	# check if the current user is the Store's owner. If not, redirect to root path

	def check_if_owner
		if current_user == Store.find(params[:id]).owner
			redirect_to dashboard_store_products_path
		else
			redirect_to root_path
		end
	end

 


end

app/controllers/products_controller.rb
 class ProductsController < ApplicationController
  layout 'customer'

  before_action :get_store


  def index
    @products = @store.products.all
    @order_line = current_order.order_lines.new
  end

  # create a new instance of OrderLine model to use in forms

  def show
    @product = @store.products.friendly.find(params[:id])

  end


private

  def get_store
    @store = Store.friendly.find(params[:store_id])
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/products/_product.html.erb
<%= form_for [:dashboard, @store, @product] do |f| %>

	<% if product.errors.any? %>
		<div class="alert alert-danger">
			<h4><%= pluralize(product.errors.count, "error") %>.</h4>
			<ul>
				<% product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

		<%= form_group_tag(product.errors[:title]) do %>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control', placeholder: "Product Name" %>
		<% end %>

		<%= form_group_tag(product.errors[:description]) do %>
			<%= f.label :description %>
			<%= f.text_area :description, rows: 6, class: 'form-control', placeholder: "Description" %>
		<% end %>

		<%= form_group_tag(product.errors[:sku]) do %>
			<%= f.label :SKU %>
			<%= f.number_field :sku, class: 'form-control', placeholder: "SKU" %>
		<% end %>

		<%= form_group_tag(product.errors[:price_in_cents]) do %>
			<%= f.label :price %>
			<%= f.number_field :price_in_cents, min: 0, class: 'form-control', placeholder: "Price" %>
		<% end %>

		<%= form_group_tag(product.errors[:count]) do %>
			<%= f.label :count %>
			<%= f.number_field :count, class: 'form-control', placeholder: "Inventory Count" %>
		<% end %>

		<%= form_group_tag(product.errors[:count]) do %>
			<%= f.label :image %>
			<%= f.file_field :image %>
			<% if f.object.image? %>
				<%= image_tag f.object.image.thumb.url %>
				<%= f.label :remove_image %>
				<%= f.check_box :remove_image %>
			<% end %>
		<% end %>


		<div class="form-group">
			<%= f.submit "Save", class: 'btn btn-success' %>
		</div>


<% end %>

app/views/dashboard/products/destroy.js.erb
$('#product_<%= @product.id %>').remove()
$('.js-products-count').html("<%= pluralize(@products.count, 'product') %>")
$("#flash").html("<%= escape_javascript(render partial: 'layouts/messages') %>")

app/views/dashboard/products/edit.html.erb
<div class="container">
	<h1>Edit Product</h1>
	<div class="row">
		<div class="col-md-3">
			<h4>Edit Product Details</h4>
		</div>
		<div class="col-md-9" id="product-input">

		<%= form_for(@product, url: dashboard_store_product_path, method: :patch) do |f| %>

			<% if @product.errors.any? %>
				<div class="alert alert-danger">
					<h4><%= pluralize(@product.errors.count, "error") %>.</h4>
					<ul>
						<% @product.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<%= form_group_tag(@product.errors[:title]) do %>
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control', :value => @product.title %>
			<% end %>

			<%= form_group_tag(@product.errors[:description]) do %>
				<%= f.label :description %>
				<%= f.text_area :description, rows: 6, class: 'form-control', :value => @product.description %>
			<% end %>

			<%= form_group_tag(@product.errors[:sku]) do %>
				<%= f.label :sku %>
				<%= f.number_field :sku, class: 'form-control', :value => @product.sku %>
			<% end %>

			<%= form_group_tag(@product.errors[:price_in_cents]) do %>
				<%= f.label :price %>
				<%= f.number_field :price_in_cents, min: 0, class: 'form-control', :value => @product.price_in_cents %>
			<% end %>

			<%= form_group_tag(@product.errors[:count]) do %>
				<%= f.label :count %>
				<%= f.number_field :count, class: 'form-control', :value => @product.count %>
			<% end %>

			<%= form_group_tag(@product.errors[:count]) do %>
				<%= f.label :image %>
				<%= f.file_field :image %>
				<% if f.object.image? %>
					<%= image_tag f.object.image.thumb.url %>
					<%= f.label :remove_image %>
					<%= f.check_box :remove_image %>
				<% end %>
			<% end %>


			<div class="form-group">
				<%= f.submit "Save", class: "btn btn-success" %>
			</div>


		<% end %>



		</div>
	</div>
</div>

app/views/dashboard/products/index.html.erb
<div class="container">
       <h2 class="js-products-count"><%= @products.count %> products </h2>
</div>

<div class="container-fluid">
        <table>
            <thead>
                <tr>
                    <th class="list-title">Item Name</th>
                    <th class="list-title">Description</th>
                    <th class="list-title">Image URL</th>
                    <th class="list-title">Price</th>
                    <th class="list-title">SKU</th>
                    <th class="list-title">Product Details</th>
                    <th class="list-title">Edit Product</th>
                    <th class="list-title">Delete Product</th>
                </tr>
            </thead>

            <tbody class="list-item">
                <% @products.each do |product| %>
                <tr id="product_<%= product.id %>">
                    <td><%= product.title %></td>
                    <td><%= product.description %></td>
                    <td>DISPLAY IMG</td>
                    <td><%= product.price %></td>
                    <td><%= product.sku %></td>
                    <td><%= link_to 'Show', dashboard_store_product_path(@store.id, product.id) %></td>
                    <td><%= link_to 'Edit', edit_dashboard_store_product_path(@store.id, product.id) %></td>
                    <td><%= link_to 'Delete', dashboard_store_product_path(@store.id, product.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>

<div class="container">
    <%= link_to "Add New Product", new_dashboard_store_product_path(@store.id, @product), class: "btn btn-success"%>
</div>

    
</div>

app/views/dashboard/products/new.html.erb
<div class="container">
	<h1>New Product</h1>
	<div class="row">
		<div class="col-md-10" id="product-input">
			<%= render partial: 'product', locals: { store: @store, product: @product } %>
		</div>
	</div>
</div>

app/views/dashboard/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<img class="img-responsive" src="http://placehold.it/400x250/000/fff" alt="" />
		</div>
		<div class="col-md-5 col-md-offset-2">
			<div id="product-title">
				<h1><%= @product.title %></h1>
			</div>
			<div id="product-price">
				<h4>Price: $<%= @product.price %></h4>
			</div>
			<div id="product-description">
				<h4 class="lead"><%= @product.description %></h4>
			</div>
			<div id="product-image">
				<h4 class="lead"><%= image_tag @product.image.thumb.url %></h4>
			</div>
			<h4><%= link_to 'Edit Product', edit_dashboard_store_product_path(current_store.id, @product.id), class: 'btn btn-success' %></h4>
        	<br />

       		<h4><%= link_to 'Delete Product', dashboard_store_product_path(current_store.id, @product.id), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %></h4>

		</div>
	</div>
</div>