config/routes.rb
Rails.application.routes.draw do

  scope '/dashboard' do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end 

  scope '/:store_id' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :dashboard do 
      root 'products#index'
      resources :stores, only: [:new, :create, :edit, :update], path: '/' do 
        resources :products
        resources :orders, only: [:index, :show, :destroy]
        resources :order_lines, only: [:index, :show]
        resources :customers, only: [:index]
      end
  end

   

  root 'welcome#index'

  get ':store_id', to: 'stores#show', as: 'store'
  resources :stores, only: [:show], path: '/' do 
    resource :cart, only: [:show]
    resources :products, only: [:index, :show]
    resources :orders, only: [:index, :show]
    get '/orders/:id/confirmation' => 'orders#confirmation', as: 'confirmation'
    resources :order_lines, only: [:create, :update, :destroy]
    resources :charges, only: [:new, :create]
  end   

end

app/models/store.rb
class Store < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged

	belongs_to :owner
	# class_name: 'User', foreign_key: 'user_id'
	has_many :products
	has_many :orders
	
	has_many :memberships, :dependent => :destroy
	has_many :customers, through: :memberships

	validates :owner, presence: true
	validates :name, presence: true, uniqueness: true
	validates_exclusion_of :name, in: %w[www ecommerce contactus faq terms]

end

app/controllers/dashboard/customers_controller.rb
class Dashboard::CustomersController < DashboardController

before_action :get_store
before_action :authenticate_owner!

def index
	@customers = @store.customers.all
end

# def show
# 	@customer = @store.customers.find(params[:id])
# end



	private

	def get_store
	  @store = Store.friendly.find(params[:store_id])
	end


end

app/controllers/dashboard/order_lines_controller.rb
class Dashboard::OrderLinesController < DashboardController

    before_action :authenticate_owner!
	before_action :get_store, only: [:index, :show]

	def index
		@order = @store.orders.find(params[:order_id])
		@order_lines = @order.order_lines.all 
	end

	def show
		@order = @store.orders.find(params[:order_id])
		@order_line = @store.orders.find(params[:id])
	end

	
	private
  
	  def order_line_params
	    params.require(:order_line).permit(:product, :order, :quantity, :price)
	  end

	  def get_store
	  	@store = Store.friendly.find(params[:store_id])
	  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < DashboardController

#order belongs to a store
    before_action :authenticate_owner!
	before_action :get_store, only: [:index, :show]

	def index
		@orders = @store.orders.all
	end

	def show
		@order = @store.orders.find(params[:id])
	end


	def destroy
		@order = @store.orders.find(params[:id])
	    authorize @order 
	    
	    if @order.destroy
	      flash[:notice] = "Order was deleted successfully."
	      redirect_to :index
	    else
	      flash[:error] = "There was an error deleting the order."
	      render :show
	    end
	end

 private
  
  def order_params
     params.require(:order).permit(:customer, :total, :completed, :date_paid)
  end

  def get_store
	 @store = Store.friendly.find(params[:store_id])
  end

end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController

  # before_action :authenticate_owner!, except: [:index, :new]
  before_action :get_store

  after_filter { flash.discard if request.xhr? }

  def index
    @products = @store.products.all
  end

  def show
    @product = Product.friendly.find(params[:id])
  end

  def new
    @product = Product.new
    authorize @product
  end


  def create
    @product = Product.new
    @product = @store.products.build(product_params)

    authorize @product

    if @product.save
      flash[:notice] = "Product was added to store"
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error saving the product."
      render :new
    end
  end


  def edit
    @product = Product.friendly.find(params[:id])
    authorize @product
  end


  def update
    @product = Product.friendly.find(params[:id])
    authorize @product

    @product.assign_attributes(product_params)

    if @product.save
      flash[:notice] = "Product was updated."
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error saving the product. Please try again."
      render :edit
    end
  end

  def destroy
    @product = Product.friendly.find(params[:id])
    authorize @product

    if @product.destroy
      flash[:notice] = "\"#{@product.title}\" was deleted successfully."
    else
      flash[:error] = "There was an error deleting the product."
    end
    @products = @store.products.all

    if @product.delete
      flash[:notice] = "Product was deleted."
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error deleting the product. Please try again."
      render :index
    end
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :sku, :price_in_cents, :count, :image, :remove_image)
  end


  def get_store
   @store = Store.friendly.find(params[:store_id])
  end

end

app/controllers/dashboard/stores_controller.rb
class Dashboard::StoresController < DashboardController

    before_action :authenticate_owner!, only: [:edit, :update]

	def show
		@store = Store.friendly.find(params[:id])
	end

	def new
		@store = Store.new
	end

	def create
		@owner = current_user
		@store = @owner.stores.build(store_params)

		if @store.save
			flash[:notice] = "Store was created."
	  		redirect_to dashboard_store_products_path(@store.id)
	    else
	      flash[:error] = "There was an error creating the store."
	      render :new
	    end
  	end


   	def edit
   		@store = Store.friendly.find(params[:id])
   	end


	 def update
	 	@store = Store.friendly.find(params[:id])
	 	@store.assign_attributes(store_params)

	 	if @store.save
	 		flash[:notice] = "Store was updated."
	 		redirect_to dashboard_store_products_path
	 	else
	 		flash[:error] = "There was an error updating the store. Please try again."
	 		render :edit
	 	end
	 end


  private

  def store_params
    params.require(:store).permit(:name, :owner_id, :description, :about, :action_call)
  end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	layout 'dashboard'
	# to correspond with the dashboard layouts for view 

	# before_action :check_if_owner

	# check if the current user is the Store's owner. If not, redirect to root path

	def check_if_owner
		if current_user == Store.find(params[:id]).owner
			redirect_to dashboard_store_products_path
		else
			redirect_to root_path
		end
	end

 


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

layout 'customer'

	def show
		@store = Store.friendly.find(params[:store_id])
	end


end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/dashboard/stores/edit.html.erb
<div class="container">
	<h1>Update Your Store</h1>
	<div class="row">
		
		<div class="container">
			<%= form_for(@store, url: dashboard_store_path, method: :patch) do |f| %>

				<% if @store.errors.any? %>
					<div class="alert alert-danger">
						<h4><%= pluralize(@store.errors.count, "error") %>.</h4>
						<ul>
							<% @store.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>	

				<%= form_group_tag(@store.errors[:name]) do %>
					<%= f.label :store_name %>
					<%= f.text_field :name, class: 'form-control', placeholder: "Store Name" %>
				<% end %>
            
                <%= form_group_tag(@store.errors[:description]) do %>
					<%= f.label :store_description %>
					<%= f.text_field :about, class: 'form-control', placeholder: "Brief description about your store" %>
				<% end %>
            
                <%= form_group_tag(@store.errors[:about]) do %>
					<%= f.label :store_about %>
					<%= f.text_field :description, class: 'form-control', placeholder: "What is your story?" %>
				<% end %>
            
                <%= form_group_tag(@store.errors[:action_call]) do %>
					<%= f.label :store_action_call %>
					<%= f.text_field :action_call, class: 'form-control', placeholder: "Place your call to action here" %>
				<% end %>

				<%= form_group_tag(@store.errors[:owner_id]) do %>
					<%= f.hidden_field :owner_id, :value => current_user.id %>
				<% end %>	

				<div class="form-group">
					<%= f.submit "Save", class: 'btn btn-success' %>
				</div>

			
            <% end %>
            
            
		</div>
	</div>
</div>

app/views/dashboard/stores/new.html.erb
<div class="container">
	<h1>Create Your Store</h1>
	<div class="row">
		
		<div class="container">
			<%= form_for :store, url: dashboard_stores_path do |f| %>

				<% if @store.errors.any? %>
					<div class="alert alert-danger">
						<h4><%= pluralize(@store.errors.count, "error") %>.</h4>
						<ul>
							<% @store.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>	

				<%= form_group_tag(@store.errors[:name]) do %>
					<%= f.label :store_name %>
					<%= f.text_field :name, class: 'form-control', placeholder: "Store Name" %>
				<% end %>

				<%= form_group_tag(@store.errors[:owner_id]) do %>
					<%= f.hidden_field :owner_id, :value => current_user.id %>
				<% end %>	

				<div class="form-group">
					<%= f.submit "Save", class: 'btn btn-success' %>
				</div>

			<% end %>
		</div>
	</div>
</div>