config/routes.rb
Rails.application.routes.draw do

  scope '/dashboard' do 
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end 

  scope '/:store_id' do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :dashboard do 
      root 'products#index'
      resources :stores, only: [:new, :create, :edit, :update], path: '/' do 
        resources :products
        resources :orders, only: [:index, :show, :destroy]
        resources :order_lines, only: [:index, :show]
        resources :customers, only: [:index]
      end
  end

   

  root 'welcome#index'

  get ':store_id', to: 'stores#show', as: 'store'
  resources :stores, only: [:show], path: '/' do 
    resource :cart, only: [:show]
    resources :products, only: [:index, :show]
    resources :orders, only: [:index, :show]
    get '/orders/:id/confirmation' => 'orders#confirmation', as: 'confirmation'
    resources :order_lines, only: [:create, :update, :destroy]
    resources :charges, only: [:new, :create]
  end   

end

app/models/order.rb
class Order < ActiveRecord::Base


	belongs_to :customer
	belongs_to :guest
	belongs_to :store
	has_many :order_lines

	validates :guest, presence: true, allow_nil: true
	validates :customer, presence: true, allow_nil: true



	
	def subtotal
		order_lines.collect { |ol| ol.present? ? ol.total_price : 0 }.sum
	end

	def total_items
		order_lines.sum(:quantity)
	end



end

app/controllers/dashboard/customers_controller.rb
class Dashboard::CustomersController < DashboardController

before_action :get_store
before_action :authenticate_owner!

def index
	@customers = @store.customers.all
end

# def show
# 	@customer = @store.customers.find(params[:id])
# end



	private

	def get_store
	  @store = Store.friendly.find(params[:store_id])
	end


end

app/controllers/dashboard/order_lines_controller.rb
class Dashboard::OrderLinesController < DashboardController

    before_action :authenticate_owner!
	before_action :get_store, only: [:index, :show]

	def index
		@order = @store.orders.find(params[:order_id])
		@order_lines = @order.order_lines.all 
	end

	def show
		@order = @store.orders.find(params[:order_id])
		@order_line = @store.orders.find(params[:id])
	end

	
	private
  
	  def order_line_params
	    params.require(:order_line).permit(:product, :order, :quantity, :price)
	  end

	  def get_store
	  	@store = Store.friendly.find(params[:store_id])
	  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < DashboardController

#order belongs to a store
    before_action :authenticate_owner!
	before_action :get_store, only: [:index, :show]

	def index
		@orders = @store.orders.all
	end

	def show
		@order = @store.orders.find(params[:id])
	end


	def destroy
		@order = @store.orders.find(params[:id])
	    authorize @order 
	    
	    if @order.destroy
	      flash[:notice] = "Order was deleted successfully."
	      redirect_to :index
	    else
	      flash[:error] = "There was an error deleting the order."
	      render :show
	    end
	end

 private
  
  def order_params
     params.require(:order).permit(:customer, :total, :completed, :date_paid)
  end

  def get_store
	 @store = Store.friendly.find(params[:store_id])
  end

end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < DashboardController

  # before_action :authenticate_owner!, except: [:index, :new]
  before_action :get_store

  after_filter { flash.discard if request.xhr? }

  def index
    @products = @store.products.all
  end

  def show
    @product = Product.friendly.find(params[:id])
  end

  def new
    @product = Product.new
    authorize @product
  end


  def create
    @product = Product.new
    @product = @store.products.build(product_params)

    authorize @product

    if @product.save
      flash[:notice] = "Product was added to store"
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error saving the product."
      render :new
    end
  end


  def edit
    @product = Product.friendly.find(params[:id])
    authorize @product
  end


  def update
    @product = Product.friendly.find(params[:id])
    authorize @product

    @product.assign_attributes(product_params)

    if @product.save
      flash[:notice] = "Product was updated."
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error saving the product. Please try again."
      render :edit
    end
  end

  def destroy
    @product = Product.friendly.find(params[:id])
    authorize @product

    if @product.destroy
      flash[:notice] = "\"#{@product.title}\" was deleted successfully."
    else
      flash[:error] = "There was an error deleting the product."
    end
    @products = @store.products.all

    if @product.delete
      flash[:notice] = "Product was deleted."
      redirect_to dashboard_store_products_path
    else
      flash[:error] = "There was an error deleting the product. Please try again."
      render :index
    end
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :sku, :price_in_cents, :count, :image, :remove_image)
  end


  def get_store
   @store = Store.friendly.find(params[:store_id])
  end

end

app/controllers/dashboard/stores_controller.rb
class Dashboard::StoresController < DashboardController

    before_action :authenticate_owner!, only: [:edit, :update]

	def show
		@store = Store.friendly.find(params[:id])
	end

	def new
		@store = Store.new
	end

	def create
		@owner = current_user
		@store = @owner.stores.build(store_params)

		if @store.save
			flash[:notice] = "Store was created."
	  		redirect_to dashboard_store_products_path(@store.id)
	    else
	      flash[:error] = "There was an error creating the store."
	      render :new
	    end
  	end


   	def edit
   		@store = Store.friendly.find(params[:id])
   	end


	 def update
	 	@store = Store.friendly.find(params[:id])
	 	@store.assign_attributes(store_params)

	 	if @store.save
	 		flash[:notice] = "Store was updated."
	 		redirect_to dashboard_store_products_path
	 	else
	 		flash[:error] = "There was an error updating the store. Please try again."
	 		render :edit
	 	end
	 end


  private

  def store_params
    params.require(:store).permit(:name, :owner_id, :description, :about, :action_call)
  end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	layout 'dashboard'
	# to correspond with the dashboard layouts for view 

	# before_action :check_if_owner

	# check if the current user is the Store's owner. If not, redirect to root path

	def check_if_owner
		if current_user == Store.find(params[:id]).owner
			redirect_to dashboard_store_products_path
		else
			redirect_to root_path
		end
	end

 


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	layout 'customer'

	before_action :get_store, only: [:index, :show]

	def index
		# @orders = @store.orders.all
		customer = Customer.find(params[:current_customer_id])
		@orders = customer.orders.all
	end

	def show
		@order = @store.orders.find(params[:id])
	end

	def confirmation
		@order = @store.orders.find(params[:id])
		@customer = @order.customer
	end


 private

#   def order_params
#      params.permit(:order).permit(:customer, :price_in_cents, :completed, :date_paid, :charge, :guest)
#   end

  def get_store
  	@store = Store.friendly.find(params[:store_id])
  end

  # need to scope based on customer (store, then customer)


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/dashboard/orders/_customer.html.erb
<h3>Customer Information</h3>
<br>
<h3><%= customer.name %></h3>
<br>
<h4><%= customer.street_address %></h4>
<br>
<h4><%= customer.city %></h4>, <h4><%= customer.state %></h4> <h4><%= customer.zip_code %></h4>
<br>
<h4><%= customer.email %></h4>
<br>
<h4><%= customer.phone_number %></h4>

app/views/dashboard/orders/index.html.erb
<div class="main">
  <h1>All Orders</h1>
  	<table>
      <thead>
          <tr>
            <th class="list-title">Order ID</th>
            <th class="list-title">Date Created</th>
            <th class="list-title">Total Price</th>
            <th class="list-title">Customer</th>
            <th class="list-title">
              Order Details</th>
          </tr>
      </thead>

      <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td class="list-item"><%= order.id %></td>
            <td class="list-item"><%= order.created_at %></td>
            <td class="list-item"><%= order.price_in_cents %></td>
            <td class="list-item"><%= order.id %></td>
            <td class="list-item"><%= link_to 'Show', dashboard_store_order_path(@store.id, order.id) %></td>
           
          </tr>
        <% end %>
      </tbody>
    </table>

</div>

app/views/dashboard/orders/show.html.erb
<div class="main">
  <h2>Order Summary</h2>
  	<div class="container">
		<div class="col-md-3">
  			<%= render 'customer', customer: @order.customer %>
  		</div>

  		<div class="col-md-9">
  			<h2>Items Ordered</h2>
  			<table class="table table-striped">
  				<thead>
  					<tr>
  						<th>Item Name</th>
  						<th>Unit Price</th>
  						<th>Quantity</th>
  						<th>Total Price</th>
  					</tr>
  				</thead>

  				<tbody>
  					<% @order.order_lines.each do |order_line| %>
  					<tr> 
  						<td><%= link_to order_line.product.title, store_product_path %></td>
              <td>$<%= order_line.product.price_in_cents %></td>
              <td><%= order_line.quantity %></td>
              <td>$<%= order_line.total_price %></td>
  					</tr>
  					<% end %>

  				</tbody>
  			</table>

  		</div>
  	</div>

</div>